version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: spring_error_handler_mysql_db
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: error_handler
      MYSQL_USER: spring_error_handler_user
      MYSQL_PASSWORD: spring_error_handlerpassword
volumes:
  mysql_data:
