spring:
  application:
    name: error-handler
  datasource:
    url: jdbc:mysql://localhost:3308/error_handler
    username: spring_error_handler_user
    password: spring_error_handlerpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate.transaction.jta.platform: none
    hibernate:
      ddl-auto: update
server:
  port: 8081
